# https://circleci.com/docs/2.0/language-javascript/
# https://hub.docker.com/r/circleci/node/tags/
# https://circleci.com/docs/2.0/language-javascript/
# https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml
version: 2
jobs:
  "node-6":
    docker:
      - image: circleci/node:6@sha256:e49c8c74394f369f60e24d0dec65b4097058769d68e44536a96bcfc67e934d01
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test

  "node-8":
    docker:
      - image: circleci/node:8@sha256:257fdc7e2949a9576e1a96364e0428d461d0505167c70dcc3e6c3825ce8a6557
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test

  "node-9":
    docker:
      - image: circleci/node:9@sha256:f08acb30cef8d8077e7b5f912092b40e390d67de845ce09f36bc818d741b5c04
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test

workflows:
  version: 2
  build:
    jobs:
      - "node-6"
      - "node-8"
      - "node-9"
